// Generated by CoffeeScript 1.7.1
var AuthConfigLoader, RikkiTikkiAPI, Util,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

RikkiTikkiAPI = module.parent.exports.RikkiTikkiAPI || module.parent.exports;

Util = RikkiTikkiAPI.Util;

AuthConfigLoader = (function(_super) {
  __extends(AuthConfigLoader, _super);

  function AuthConfigLoader(path) {
    AuthConfigLoader.__super__.constructor.call(this, null);
    this.__path = path;
  }

  AuthConfigLoader.prototype.load = function(callback) {
    if (fs.existsSync(this.__path)) {
      return AuthConfigLoader.__super__.load.call(this, (function(_this) {
        return function(e, data) {
          if (data != null) {
            _this.__data = JSON.parse(data);
          }
          return typeof callback === "function" ? callback(e, _this.__data) : void 0;
        };
      })(this));
    } else {
      return typeof callback === "function" ? callback(new Error("Could not find config file at '" + this.__path + "'")) : void 0;
    }
  };

  AuthConfigLoader.prototype.getEnvironment = function(env) {
    var _ref;
    return ((_ref = this.__data) != null ? _ref[env] : void 0) || null;
  };

  return AuthConfigLoader;

})(RikkiTikkiAPI.base_classes.AbstractLoader);

module.exports = AuthConfigLoader;
